stages:
  - pull-github

variables:
  GIT_STRATEGY: clone			#This seems to have no effect also set in webinterface
  GIT_DEPTH: 0					#This seems to have no effect also set in webinterface
  GIT_SUBMODULE_STRATEGY: recursive

pull:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $CI_COMMIT_BRANCH == "master"'
  image: ubuntu:20.04
  tags:
    - docker
  stage: pull-github
  before_script:
    - apt-get update -y
    - apt-get install -y git
  script:
    - chmod +x ./pull.sh
    - pull.sh
